// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEzyj_7Nuc7P2XM95-sF-n7AR0vd8Wjac',
    appId: '1:759218003962:web:6553e5fa1a95e28c6a8e43',
    messagingSenderId: '759218003962',
    projectId: 'startupsindia-mediaplatform',
    authDomain: 'startupsindia-mediaplatform.firebaseapp.com',
    storageBucket: 'startupsindia-mediaplatform.firebasestorage.app',
    measurementId: 'G-9SJLTRTESJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo3oMNnMHVxLAgfaojQ_IqAxXJSh-fnJQ',
    appId: '1:759218003962:android:52c45faf54a4284f6a8e43',
    messagingSenderId: '759218003962',
    projectId: 'startupsindia-mediaplatform',
    storageBucket: 'startupsindia-mediaplatform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGKdCHNCtSdkdgjS6db8lYnaDuVtofH6I',
    appId: '1:759218003962:ios:bafc75b82de8c4766a8e43',
    messagingSenderId: '759218003962',
    projectId: 'startupsindia-mediaplatform',
    storageBucket: 'startupsindia-mediaplatform.firebasestorage.app',
    iosBundleId: 'com.example.startupsIndiaMediaPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGKdCHNCtSdkdgjS6db8lYnaDuVtofH6I',
    appId: '1:759218003962:ios:bafc75b82de8c4766a8e43',
    messagingSenderId: '759218003962',
    projectId: 'startupsindia-mediaplatform',
    storageBucket: 'startupsindia-mediaplatform.firebasestorage.app',
    iosBundleId: 'com.example.startupsIndiaMediaPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEzyj_7Nuc7P2XM95-sF-n7AR0vd8Wjac',
    appId: '1:759218003962:web:b26cb88592316ecd6a8e43',
    messagingSenderId: '759218003962',
    projectId: 'startupsindia-mediaplatform',
    authDomain: 'startupsindia-mediaplatform.firebaseapp.com',
    storageBucket: 'startupsindia-mediaplatform.firebasestorage.app',
    measurementId: 'G-FBKBEVMX6G',
  );
}
