import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'firebase_options.dart'; // generated by: flutterfire configure
import 'theme/app_theme.dart';
import 'core/providers/theme_service_provider.dart';

import 'features/auth/presentation/screens/onboarding_screen.dart';
import 'features/auth/presentation/screens/login_screen.dart';
import 'features/auth/presentation/screens/signup_screen.dart';
import 'features/auth/presentation/screens/fill_profile_screen.dart';
import 'features/onboarding/presentation/screens/select_country_screen.dart';
import 'features/onboarding/presentation/screens/choose_topics_screen.dart';
import 'features/onboarding/presentation/screens/choose_news_sources_screen.dart';
import 'features/home/presentation/screens/main_app_scaffold.dart';
import 'features/home/presentation/screens/trending_screen.dart';
import 'features/home/presentation/screens/notifications_screen.dart';
import 'features/profile/presentation/screens/create_post_screen.dart';
import 'features/profile/presentation/screens/edit_profile_screen.dart';
import 'features/profile/presentation/screens/settings_screen.dart';

final GlobalKey<ScaffoldMessengerState> rootScaffoldMessengerKey =
    GlobalKey<ScaffoldMessengerState>();

final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

const AndroidNotificationChannel _highImportanceChannel =
    AndroidNotificationChannel(
      'high_importance_channel',
      'High Importance Notifications',
      description: 'This channel is used for important notifications.',
      importance: Importance.high,
    );

final FlutterLocalNotificationsPlugin _localNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  debugPrint('FCM background message: ${message.messageId}');
}

Future<void> _initializeLocalNotifications() async {
  const androidSettings = AndroidInitializationSettings('@mipmap/ic_launcher');
  const iosSettings = DarwinInitializationSettings();
  const settings = InitializationSettings(
    android: androidSettings,
    iOS: iosSettings,
  );

  await _localNotificationsPlugin.initialize(settings);

  await _localNotificationsPlugin
      .resolvePlatformSpecificImplementation<
        AndroidFlutterLocalNotificationsPlugin
      >()
      ?.createNotificationChannel(_highImportanceChannel);
}

Future<void> _showForegroundLocalNotification(RemoteMessage message) async {
  final notification = message.notification;
  if (notification == null) return;

  const androidDetails = AndroidNotificationDetails(
    'high_importance_channel',
    'High Importance Notifications',
    channelDescription: 'This channel is used for important notifications.',
    importance: Importance.high,
    priority: Priority.high,
  );
  const iosDetails = DarwinNotificationDetails();

  const details = NotificationDetails(android: androidDetails, iOS: iosDetails);

  await _localNotificationsPlugin.show(
    message.hashCode,
    notification.title,
    notification.body,
    details,
  );
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialise Firebase before anything else
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Firestore is available after Firebase initialization; pre-configure it once.
  FirebaseFirestore.instance.settings = const Settings(
    persistenceEnabled: true,
  );

  await _initializeLocalNotifications();

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  final notificationSettings = await FirebaseMessaging.instance
      .requestPermission(
        alert: true,
        badge: true,
        sound: true,
        provisional: false,
      );
  debugPrint(
    'FCM permission status: ${notificationSettings.authorizationStatus}',
  );

  try {
    final token = await FirebaseMessaging.instance.getToken();
    debugPrint('FCM token: $token');
  } catch (e) {
    debugPrint('FCM token unavailable: $e');
  }

  // Initialize Google Sign-In singleton (Required in v7.0.0+).
  // On Web, the clientId is read from the <meta name="google-signin-client_id"> tag
  // in web/index.html — see README for setup. Skip on web until that is configured.
  if (!kIsWeb) {
    await GoogleSignIn.instance.initialize();
  }

  final prefs = await SharedPreferences.getInstance();
  final bool isFirstRun = prefs.getBool('isFirstRun') ?? true;

  runApp(ProviderScope(child: MyApp(isFirstRun: isFirstRun)));
}

class MyApp extends ConsumerStatefulWidget {
  final bool isFirstRun;
  const MyApp({super.key, required this.isFirstRun});

  @override
  ConsumerState<MyApp> createState() => _MyAppState();
}

class _MyAppState extends ConsumerState<MyApp> {
  StreamSubscription<RemoteMessage>? _foregroundMessageSubscription;

  @override
  void initState() {
    super.initState();
    _foregroundMessageSubscription = FirebaseMessaging.onMessage.listen((
      message,
    ) {
      final title = message.notification?.title ?? 'Notification';
      final body = message.notification?.body ?? 'You have a new update.';

      rootScaffoldMessengerKey.currentState?.showSnackBar(
        SnackBar(
          content: Text('$title: $body'),
          action: SnackBarAction(
            label: 'View',
            onPressed: () => _handleMessage(message),
          ),
          behavior: SnackBarBehavior.floating,
        ),
      );

      unawaited(_showForegroundLocalNotification(message));
    });

    // Handle tap from background state
    FirebaseMessaging.onMessageOpenedApp.listen(_handleMessage);

    // Handle tap from terminated state
    FirebaseMessaging.instance.getInitialMessage().then((message) {
      if (message != null) {
        // App started by tapping on a notification
        _handleMessage(message);
      }
    });
  }

  void _handleMessage(RemoteMessage message) {
    if (message.data.containsKey('page')) {
      final page = message.data['page'];
      if (page == 'notifications') {
        navigatorKey.currentState?.pushNamed('/notifications');
      }
      // Add other page navigations here based on payload
    }
  }

  @override
  void dispose() {
    _foregroundMessageSubscription?.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final themeMode = ref.watch(themeServiceProvider);

    return MaterialApp(
      navigatorKey: navigatorKey,
      scaffoldMessengerKey: rootScaffoldMessengerKey,
      debugShowCheckedModeBanner: false,
      title: 'News App',
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: themeMode,
      initialRoute: widget.isFirstRun ? '/onboarding' : '/login',
      routes: {
        '/onboarding': (context) => const OnboardingScreen(),
        '/login': (context) => const LoginScreen(),
        '/signup': (context) => const SignupScreen(),
        '/topics': (context) => const ChooseTopicsScreen(),
        '/news-sources': (context) => const ChooseNewsSourcesScreen(),
        '/fill-profile': (context) => const FillProfileScreen(),
        '/select-country': (context) => const SelectCountryScreen(),
        '/home': (context) => const MainAppScaffold(initialIndex: 0),
        '/explore': (context) => const MainAppScaffold(initialIndex: 1),
        '/trending': (context) => const TrendingScreen(),
        '/notifications': (context) => const NotificationsScreen(),
        '/settings': (context) => const SettingsScreen(),
        '/create-post': (context) => const CreatePostScreen(),
        '/edit-profile': (context) => const EditProfileScreen(),
      },
    );
  }
}
